/*
 *
 * LurinFvMaintenanceZoneContainer constants
 *
 */

export const LOAD_COMMERCIAL_ZONES_ACTION = 'LOAD_COMMERCIAL_ZONES_ACTION';
export const LOAD_COMMERCIAL_ZONES_ACTION_SUCCESS = 'LOAD_COMMERCIAL_ZONES_ACTION_SUCCESS';
export const LOAD_COMMERCIAL_ZONES_ACTION_FAILURE = 'LOAD_COMMERCIAL_ZONES_ACTION_FAILURE';
export const SHOW_ZONES_FORM_ACTION = 'SHOW_ZONES_FORM_ACTION';
export const CREATE_COMMERCIAL_ZONES_ACTION = 'CREATE_COMMERCIAL_ZONES_ACTION';
export const CREATE_COMMERCIAL_ZONES_ACTION_SUCCESS = 'CREATE_COMMERCIAL_ZONES_ACTION_SUCCESS';
export const CREATE_COMMERCIAL_ZONES_ACTION_FAILURE = 'CREATE_COMMERCIAL_ZONES_ACTION_FAILURE';
export const UPDATE_COMMERCIAL_ZONES_ACTION = 'UPDATE_COMMERCIAL_ZONES_ACTION';
export const UPDATE_COMMERCIAL_ZONES_ACTION_SUCCESS = 'UPDATE_COMMERCIAL_ZONES_ACTION_SUCCESS';
export const UPDATE_COMMERCIAL_ZONES_ACTION_FAILURE = 'UPDATE_COMMERCIAL_ZONES_ACTION_FAILURE';
export const DELETE_COMMERCIAL_ZONES_ACTION = 'DELETE_COMMERCIAL_ZONES_ACTION';
export const DELETE_COMMERCIAL_ZONES_ACTION_SUCCESS = 'DELETE_COMMERCIAL_ZONES_ACTION_SUCCESS';
export const DELETE_COMMERCIAL_ZONES_ACTION_FAILURE = 'DELETE_COMMERCIAL_ZONES_ACTION_FAILURE';
