/*
 *
 * LurinFvGlobalParameterContainer constants
 *
 */

export const LOAD_SECURITYPOLICY_ACTION = 'LOAD_SECURITYPOLICY_ACTION';
export const LOAD_SECURITYPOLICY_ACTION_SUCCESS = 'LOAD_SECURITYPOLICY_ACTION_SUCCESS';
export const LOAD_SECURITYPOLICY_ACTION_FAILURE = 'LOAD_SECURITYPOLICY_ACTION_FAILURE';
export const UPDATE_SECURITYPOLICY_ACTION = 'UPDATE_SECURITYPOLICY_ACTION';
export const UPDATE_SECURITYPOLICY_ACTION_SUCCESS = 'UPDATE_SECURITYPOLICY_ACTION_SUCCESS';
export const UPDATE_SECURITYPOLICY_ACTION_FAILURE = 'UPDATE_SECURITYPOLICY_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';
