/*
 *
 * LurinFvCampaingContainer constants
 *
 */

export const LOAD_OPERATORS_ACTION = 'LOAD_OPERATORS_ACTION';
export const LOAD_OPERATORS_ACTION_SUCCESS = 'LOAD_OPERATORS_ACTION_SUCCESS';
export const LOAD_OPERATORS_ACTION_FAILURE = 'LOAD_OPERATORS_ACTION_FAILURE';
export const SHOW_OPERATORS_FORM_ACTION = 'SHOW_OPERATORS_FORM_ACTION';
export const CREATE_OPERATORS_ACTION = 'CREATE_OPERATORS_ACTION';
export const CREATE_OPERATORS_ACTION_SUCCESS = 'CREATE_OPERATORS_ACTION_SUCCESS';
export const CREATE_OPERATORS_ACTION_FAILURE = 'CREATE_OPERATORS_ACTION_FAILURE';
export const UPDATE_OPERATORS_ACTION = 'UPDATE_OPERATORS_ACTION';
export const UPDATE_OPERATORS_ACTION_SUCCESS = 'UPDATE_OPERATORS_ACTION_SUCCESS';
export const UPDATE_OPERATORS_ACTION_FAILURE = 'UPDATE_OPERATORS_ACTION_FAILURE';
export const DELETE_OPERATORS_ACTION = 'DELETE_OPERATORS_ACTION';
export const DELETE_OPERATORS_ACTION_SUCCESS = 'DELETE_OPERATORS_ACTION_SUCCESS';
export const DELETE_OPERATORS_ACTION_FAILURE = 'DELETE_OPERATORS_ACTION_FAILURE';

export const LOAD_DATASOURCES_ACTION = 'LOAD_DATASOURCES_ACTION';
export const LOAD_DATASOURCES_ACTION_SUCCESS = 'LOAD_DATASOURCES_ACTION_SUCCESS';
export const LOAD_DATASOURCES_ACTION_FAILURE = 'LOAD_DATASOURCES_ACTION_FAILURE';


export const LOAD_JNDI_ACTION = 'LOAD_JNDI_ACTION';
export const LOAD_JNDI_ACTION_SUCCESS = 'LOAD_JNDI_ACTION_SUCCESS';
export const LOAD_JNDI_ACTION_FAILURE = 'LOAD_JNDI_ACTION_FAILURE';

export const LOAD_CAS_ACTION = 'LOAD_CAS_ACTION';
export const LOAD_CAS_ACTION_SUCCESS = 'LOAD_CAS_ACTION_SUCCESS';
export const LOAD_CAS_ACTION_FAILURE = 'LOAD_CAS_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';

