/*
 *
 * LurinFvCampaingContainer constants
 *
 */

export const LOAD_PROFILES_ACTION = 'LOAD_PROFILES_ACTION';
export const LOAD_PROFILES_ACTION_SUCCESS = 'LOAD_PROFILES_ACTION_SUCCESS';
export const LOAD_PROFILES_ACTION_FAILURE = 'LOAD_PROFILES_ACTION_FAILURE';
export const SHOW_PROFILES_FORM_ACTION = 'SHOW_PROFILES_FORM_ACTION';
export const CREATE_PROFILES_ACTION = 'CREATE_PROFILES_ACTION';
export const CREATE_PROFILES_ACTION_SUCCESS = 'CREATE_PROFILES_ACTION_SUCCESS';
export const CREATE_PROFILES_ACTION_FAILURE = 'CREATE_PROFILES_ACTION_FAILURE';
export const UPDATE_PROFILES_ACTION = 'UPDATE_PROFILES_ACTION';
export const UPDATE_PROFILES_ACTION_SUCCESS = 'UPDATE_PROFILES_ACTION_SUCCESS';
export const UPDATE_PROFILES_ACTION_FAILURE = 'UPDATE_PROFILES_ACTION_FAILURE';
export const DELETE_PROFILES_ACTION = 'DELETE_PROFILES_ACTION';
export const DELETE_PROFILES_ACTION_SUCCESS = 'DELETE_PROFILES_ACTION_SUCCESS';
export const DELETE_PROFILES_ACTION_FAILURE = 'DELETE_PROFILES_ACTION_FAILURE';

export const LOAD_MODULES_ACTION = 'LOAD_MODULES_ACTION';
export const LOAD_MODULES_ACTION_SUCCESS = 'LOAD_MODULES_ACTION_SUCCESS';
export const LOAD_MODULES_ACTION_FAILURE = 'LOAD_MODULES_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';

export const LOAD_PROFILES_CATEGORIES_ACTION_SUCCESS = 'LOAD_PROFILES_CATEGORIES_ACTION_SUCCESS';
export const LOAD_PROFILES_CATEGORIES_ACTION_FAILURE = 'LOAD_PROFILES_CATEGORIES_ACTION_FAILURE';
