/*
 *
 * LurinFvFreeviewManagmentContainer constants
 *
 */

export const LOAD_FREEVIEWS_ACTION = 'LOAD_FREEVIEWS_ACTION';
export const LOAD_FREEVIEWS_ACTION_SUCCESS = 'LOAD_FREEVIEWS_ACTION_SUCCESS';
export const LOAD_FREEVIEWS_ACTION_FAILURE = 'LOAD_FREEVIEWS_ACTION_FAILURE';
export const SHOW_FREEVIEWS_FORM_ACTION = 'SHOW_FREEVIEWS_FORM_ACTION';
export const CREATE_FREEVIEWS_ACTION = 'CREATE_FREEVIEWS_ACTION';
export const CREATE_FREEVIEWS_ACTION_SUCCESS = 'CREATE_FREEVIEWS_ACTION_SUCCESS';
export const CREATE_FREEVIEWS_ACTION_FAILURE = 'CREATE_FREEVIEWS_ACTION_FAILURE';
export const UPDATE_FREEVIEWS_ACTION = 'UPDATE_FREEVIEWS_ACTION';
export const UPDATE_FREEVIEWS_ACTION_SUCCESS = 'UPDATE_FREEVIEWS_ACTION_SUCCESS';
export const UPDATE_FREEVIEWS_ACTION_FAILURE = 'UPDATE_FREEVIEWS_ACTION_FAILURE';
export const DELETE_FREEVIEWS_ACTION = 'DELETE_FREEVIEWS_ACTION';
export const DELETE_FREEVIEWS_ACTION_SUCCESS = 'DELETE_FREEVIEWS_ACTION_SUCCESS';
export const DELETE_FREEVIEWS_ACTION_FAILURE = 'DELETE_FREEVIEWS_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';
