export const BACKGROUND_COLOR_FORM = '#00425A';
export const BACKGROUND_COLOR_HEADER = '#002D36';
export const BACKGROUND_COLOR_FOOTER = '#002D36';
export const BACKGROUND_COLOR_BODY = '#E9EAE8';
export const BACKGROUND_ADD_BUTTON = '#00C6D7';
export const BACKGROUND_DELETE_BUTTON = '#BB650E';
export const BACKGROUND_COLOR_SIDEBAR = '#00425A';


export const ITEM_THEME = {
  BACKGROUNDCOLOR_HEADER_PAGE: 'BACKGROUNDCOLOR-HEADER-PAGE',
  BACKGROUNDCOLOR_FOOTER_PAGE: 'BACKGROUNDCOLOR-FOOTER-PAGE',
  BACKGROUNDCOLOR_SIDEBAR_PAGE: 'BACKGROUNDCOLOR-SIDEBAR-PAGE',
  BACKGROUNDCOLOR_HEADER_FORM: 'BACKGROUNDCOLOR-HEADER-FORM',
  BACKGROUNDCOLOR_BUTTON_NEW: 'BACKGROUNDCOLOR-BUTTON-NEW',
  BACKGROUNDCOLOR_BUTTON_DELETE: 'BACKGROUNDCOLOR-BUTTON-DELETE',
  BACKGROUNDCOLOR_BUTTON_SAVE: 'BACKGROUNDCOLOR-BUTTON-SAVE',
  LOGO_URL: 'LOGO-URL'
};