/*
 *
 * LurinFvCampaingContainer constants
 *
 */

export const LOAD_USERS_CARRIER_ACTION_SUCCESS = 'LOAD_USERS_CARRIER_ACTION_SUCCESS';
export const LOAD_USERS_CARRIER_ACTION_FAILURE = 'LOAD_USERS_CARRIER_ACTION_FAILURE';
export const LOAD_USERS_ACTION = 'LOAD_USERS_ACTION';
export const LOAD_USERS_ACTION_SUCCESS = 'LOAD_USERS_ACTION_SUCCESS';
export const LOAD_USERS_ACTION_FAILURE = 'LOAD_USERS_ACTION_FAILURE';
export const LOAD_USERS_LDAP_ACTION = 'LOAD_USERS_LDAP_ACTION';
export const LOAD_USERS_LDAP_ACTION_SUCCESS = 'LOAD_USERS_LDAP_ACTION_SUCCESS';
export const LOAD_USERS_LDAP_ACTION_FAILURE = 'LOAD_USERS_LDAP_ACTION_FAILURE';
export const SHOW_USERS_FORM_ACTION = 'SHOW_USERS_FORM_ACTION';
export const CREATE_USERS_ACTION = 'CREATE_USERS_ACTION';
export const CREATE_USERS_ACTION_SUCCESS = 'CREATE_USERS_ACTION_SUCCESS';
export const CREATE_USERS_ACTION_FAILURE = 'CREATE_USERS_ACTION_FAILURE';
export const UPDATE_USERS_ACTION = 'UPDATE_USERS_ACTION';
export const UPDATE_USERS_ACTION_SUCCESS = 'UPDATE_USERS_ACTION_SUCCESS';
export const UPDATE_USERS_ACTION_FAILURE = 'UPDATE_USERS_ACTION_FAILURE';
export const DELETE_USERS_ACTION = 'DELETE_USERS_ACTION';
export const DELETE_USERS_ACTION_SUCCESS = 'DELETE_USERS_ACTION_SUCCESS';
export const DELETE_USERS_ACTION_FAILURE = 'DELETE_USERS_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';
