export const LOAD_FREVIEWDATA_ACTION = 'LOAD_FREVIEWDATA_ACTION';
export const LOAD_FREVIEWDATA_ACTION_SUCCESS = 'LOAD_FREVIEWDATA_ACTION_SUCCESS';
export const LOAD_FREVIEWDATA_ACTION_FAILURE = 'LOAD_FREVIEWDATA_ACTION_FAILURE';

export const LOAD_FREEVIEW_EXPORT_ACTION = 'LOAD_FREEVIEW_EXPORT_ACTION';
export const LOAD_FREEVIEW_EXPORT_ACTION_SUCCESS = 'LOAD_FREEVIEW_EXPORT_ACTION_SUCCESS';
export const LOAD_FREEVIEW_EXPORT_ACTION_FAILURE = 'LOAD_FREEVIEW_EXPORT_ACTION_FAILURE';

export const INIT_DOWNLOAD_ACTION = 'INIT_DOWNLOAD_ACTION';
