package com.zed.lurin.domain.jpa;// default package
// Generated 06/20/2018 10:59:06 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;

/**
 * CategoriesProfile generated by hbm2java
 */
@Entity
@Table(name="CATEGORIES_PROFILE")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class CategoriesProfile{


    @Id
    @Column(name="CATEGORIES_PROFILE_ID", unique=true, nullable=false, precision=8, scale=0)
    private int categoriesProfileId;

    @Column(name="NAME", nullable=false, length=50)
    private String name;

    @Column(name="ORDER_LOCATION", nullable=false, precision=10, scale=0)
    private long orderLocation;

//    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="categoriesProfile")
//    private Set<Profile> profiles = new HashSet<Profile>(0);

    public int getCategoriesProfileId() {
        return categoriesProfileId;
    }

    public void setCategoriesProfileId(int categoriesProfileId) {
        this.categoriesProfileId = categoriesProfileId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getOrderLocation() {
        return orderLocation;
    }

    public void setOrderLocation(long orderLocation) {
        this.orderLocation = orderLocation;
    }

}


