package com.zed.lurin.domain.jpa;


import javax.persistence.*;

/**
 * CategoriesRoles generated by hbm2java
 */
@Entity
@Table(name="CATEGORIES_ROLES")
public class CategoriesRoles {

    @Id
    @Column(name="CATEGORIES_ROLES_ID", unique=true, nullable=false, precision=8, scale=0)
    private int categoriesRolesId;

    /**
     * name of the role category
     */
    @Column(name="NAME", nullable=false, length=50)
    private String name;

    /**
     * order of the categories
     */
    @Column(name="ORDER_LOCATION", nullable=false, precision=10, scale=0)
    private long orderLocation;

    public int getCategoriesRolesId() {
        return categoriesRolesId;
    }

    public void setCategoriesRolesId(int categoriesRolesId) {
        this.categoriesRolesId = categoriesRolesId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getOrderLocation() {
        return orderLocation;
    }

    public void setOrderLocation(long orderLocation) {
        this.orderLocation = orderLocation;
    }
}


