package com.zed.lurin.domain.jpa;// default package
// Generated 04/26/2018 12:12:12 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Dictionary generated by hbm2java
 */
@Entity
@Table(name="DICTIONARY")
public class Dictionary {


    @Id
    @Column(name="DICTIONARY_ID", unique=true, nullable=false, precision=10, scale=0)
    private long code;

    @Column(name="DEFAULT_I18N", nullable=false, length=500)
    private String defaultI18n;

    @Column(name="EN", nullable=false, length=500)
    private String en;

    @Column(name="ES", nullable=false, length=500)
    private String es;

    @Column(name="PR", nullable=false, length=500)
    private String pr;

    @Column(name="ROW_ID", nullable=false, precision=10, scale=0)
    private long rowId;

    @Transient
    private String langAssigned;

    public long getCode() {
        return code;
    }

    public void setCode(long code) {
        this.code = code;
    }

    public String getDefaultI18n() {
        return defaultI18n;
    }

    public void setDefaultI18n(String defaultI18n) {
        this.defaultI18n = defaultI18n;
    }

    public String getEn() {
        return en;
    }

    public void setEn(String en) {
        this.en = en;
    }

    public String getEs() {
        return es;
    }

    public void setEs(String es) {
        this.es = es;
    }

    public String getPr() {
        return pr;
    }

    public void setPr(String pr) {
        this.pr = pr;
    }

    public long getRowId() {
        return rowId;
    }

    public void setRowId(long rowId) {
        this.rowId = rowId;
    }

    public String getLangAssigned() {
        return langAssigned;
    }

    public void setLangAssigned(String langAssigned) {
        this.langAssigned = langAssigned;
    }
}


