package com.zed.lurin.domain.jpa;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import org.hibernate.annotations.GenericGenerator;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name="PROFILE", uniqueConstraints = @UniqueConstraint(columnNames="NAME")
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Profile {

    @Id
    @Column(name="PROFILE_ID", unique=true, nullable=false, precision=10, scale=0)
    @GenericGenerator(
            name = "proIdSeq",
            strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @org.hibernate.annotations.Parameter(name = "sequence_name", value = "PROFILE_SEQ"),
                    @org.hibernate.annotations.Parameter(name = "initial_value", value = "1"),
                    @org.hibernate.annotations.Parameter(name = "increment_size", value = "1")
            }
    )
    @GeneratedValue(generator = "proIdSeq")
    private long profileId;

    @Column(name="NAME", unique=true, nullable=false, length=100)
    private String name;

    @Column(name="DESCRIPTION", length=200)
    private String description;

    /**
     * if it is visible to the public
     */
    @Column(name="VISIBLE", nullable=false, precision=1, scale=0)
    private boolean visible;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATEGORIES_PROFILE_ID", nullable=false)
    private CategoriesProfile categoriesProfile;

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="profile", orphanRemoval = true)
    @JsonManagedReference("profile-Profile")
    private Set<ProfileRoles> profileRoles = new HashSet<ProfileRoles>(0);


    public long getProfileId() {
        return profileId;
    }

    public void setProfileId(long profileId) {
        this.profileId = profileId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isVisible() {
        return visible;
    }

    public void setVisible(boolean visible) {
        this.visible = visible;
    }

    public Set<ProfileRoles> getProfileRoles() {
        return profileRoles;
    }

    public void setProfileRoles(Set<ProfileRoles> profileRoles) {
        this.profileRoles = profileRoles;
    }

    public CategoriesProfile getCategoriesProfile() {
        return categoriesProfile;
    }

    public void setCategoriesProfile(CategoriesProfile categoriesProfile) {
        this.categoriesProfile = categoriesProfile;
    }
}


