package com.zed.lurin.domain.jpa;

import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.*;

/**
 * ProfileRoles generated by hbm2java
 */
@Entity
@Table(name="PROFILE_ROLES")
public class ProfileRoles  {

    @EmbeddedId
    @AttributeOverrides( {
            @AttributeOverride(name="roleId", column=@Column(name="ROLE_ID", nullable=false, precision=10, scale=0) ),
            @AttributeOverride(name="profileId", column=@Column(name="PROFILE_ID", nullable=false, precision=10, scale=0) ),
            @AttributeOverride(name="isCreate", column=@Column(name="IS_CREATE", nullable=false, precision=1, scale=0) ),
            @AttributeOverride(name="isEdit", column=@Column(name="IS_EDIT", nullable=false, precision=1, scale=0) ),
            @AttributeOverride(name="isDelete", column=@Column(name="IS_DELETE", nullable=false, precision=1, scale=0) ),
            @AttributeOverride(name="isGet", column=@Column(name="IS_GET", nullable=false, precision=1, scale=0) ),
            @AttributeOverride(name="isAllowAll", column=@Column(name="IS_ALLOW_ALL", nullable=false, precision=1, scale=0) ) } )
    private ProfileRolesId id;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROFILE_ID", nullable=false, insertable=false, updatable=false)
    @JsonBackReference("profile-Profile")
    private Profile profile;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLE_ID", nullable=false, insertable=false, updatable=false)
    @JsonBackReference
    private Roles roles;

    public ProfileRolesId getId() {
        return id;
    }

    public void setId(ProfileRolesId id) {
        this.id = id;
    }

    public Profile getProfile() {
        return profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }

    public Roles getRoles() {
        return roles;
    }

    public void setRoles(Roles roles) {
        this.roles = roles;
    }
}


