package com.zed.lurin.domain.jpa;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * ProfileRolesId generated by hbm2java
 */
@Embeddable
public class ProfileRolesId  implements java.io.Serializable {

    @Column(name="ROLE_ID", nullable=false, precision=10, scale=0)
    private long roleId;

    @Column(name="PROFILE_ID", nullable=false, precision=10, scale=0)
    private long profileId;

    @Column(name="IS_CREATE", nullable=false, precision=1, scale=0)
    private boolean isCreate;

    @Column(name="IS_EDIT", nullable=false, precision=1, scale=0)
    private boolean isEdit;

    @Column(name="IS_DELETE", nullable=false, precision=1, scale=0)
    private boolean isDelete;

    @Column(name="IS_GET", nullable=false, precision=1, scale=0)
    private boolean isGet;

    @Column(name="IS_ALLOW_ALL", nullable=false, precision=1, scale=0)
    private boolean isAllowAll;


    public long getRoleId() {
        return roleId;
    }

    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }

    public long getProfileId() {
        return profileId;
    }

    public void setProfileId(long profileId) {
        this.profileId = profileId;
    }

    public boolean isCreate() {
        return isCreate;
    }

    public void setCreate(boolean create) {
        isCreate = create;
    }

    public boolean isEdit() {
        return isEdit;
    }

    public void setEdit(boolean edit) {
        isEdit = edit;
    }

    public boolean isDelete() {
        return isDelete;
    }

    public void setDelete(boolean delete) {
        isDelete = delete;
    }

    public boolean isGet() {
        return isGet;
    }

    public void setGet(boolean get) {
        isGet = get;
    }

    public boolean isAllowAll() {
        return isAllowAll;
    }

    public void setAllowAll(boolean allowAll) {
        isAllowAll = allowAll;
    }
}


