/*
 *
 * LurinFvCampaingContainer constants
 *
 */

export const LOAD_CAMPAINGS_ACTION = 'LOAD_CAMPAINGS_ACTION';
export const LOAD_CAMPAINGS_ACTION_SUCCESS = 'LOAD_CAMPAINGS_ACTION_SUCCESS';
export const LOAD_CAMPAINGS_ACTION_FAILURE = 'LOAD_CAMPAINGS_ACTION_FAILURE';
export const SHOW_CAMPAINGS_FORM_ACTION = 'SHOW_CAMPAINGS_FORM_ACTION';
export const CREATE_CAMPAINGS_ACTION = 'CREATE_CAMPAINGS_ACTION';
export const CREATE_CAMPAINGS_ACTION_SUCCESS = 'CREATE_CAMPAINGS_ACTION_SUCCESS';
export const CREATE_CAMPAINGS_ACTION_FAILURE = 'CREATE_CAMPAINGS_ACTION_FAILURE';
export const UPDATE_CAMPAINGS_ACTION = 'UPDATE_CAMPAINGS_ACTION';
export const UPDATE_CAMPAINGS_ACTION_SUCCESS = 'UPDATE_CAMPAINGS_ACTION_SUCCESS';
export const UPDATE_CAMPAINGS_ACTION_FAILURE = 'UPDATE_CAMPAINGS_ACTION_FAILURE';
export const DELETE_CAMPAINGS_ACTION = 'DELETE_CAMPAINGS_ACTION';
export const DELETE_CAMPAINGS_ACTION_SUCCESS = 'DELETE_CAMPAINGS_ACTION_SUCCESS';
export const DELETE_CAMPAINGS_ACTION_FAILURE = 'DELETE_CAMPAINGS_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';