export const LOAD_CAMPAIGNDATA_ACTION = 'LOAD_CAMPAIGNDATA_ACTION';
export const LOAD_CAMPAIGNDATA_ACTION_SUCCESS = 'LOAD_CAMPAIGNDATA_ACTION_SUCCESS';
export const LOAD_CAMPAIGNDATA_ACTION_FAILURE = 'LOAD_CAMPAIGNDATA_ACTION_FAILURE';

export const LOAD_CAMPAIGNDATA_EXPORT_ACTION = 'LOAD_CAMPAIGNDATA_EXPORT_ACTION';
export const LOAD_CAMPAIGNDATA_EXPORT_ACTION_SUCCESS = 'LOAD_CAMPAIGNDATA_EXPORT_ACTION_SUCCESS';
export const LOAD_CAMPAIGNDATA_EXPORT_ACTION_FAILURE = 'LOAD_CAMPAIGNDATA_EXPORT_ACTION_FAILURE';

export const INIT_DOWNLOAD_ACTION = 'INIT_DOWNLOAD_ACTION';