package com.zed.lurin.quartz.keys;

public enum QuartzKeys {
    TRIGGER_VALIDATE_TOKEN,
    TRIGGER_VALIDATE_EXPIRED_PASS,
    SCHEDULER_GROUP_LURIN ,
    JOB_VALIDATE_TOKEN,
    JOB_VALIDATE_EXPIRED_PASS,
    SCHEDULER_GROUP_CAS,
    CAMPAING_TYPE,
    CAMPAING_FREEVIEW,
    CAMPAING,
    CAMPAING_MEMBER,
    CARRIER_ID,
    IP_SERVER_CAS,
    PORT_SERVER_CAS,
    PORT_SERVER_CAS2,
    PORT_SERVER_CAS3,
    INIT_BATCH,
    END_BATCH,
    EMAIL,
    JNDI_NAME
}
