/*
 *
 * LurinFvGlobalParameterContainer constants
 *
 */

export const LOAD_USERDATA_BYNAME_ACTION  = 'LOAD_USERDATA_BYNAME_ACTION';
export const LOAD_USERDATA_BYNAME_ACTION_SUCCESS  = 'LOAD_USERDATA_BYNAME_ACTION_SUCCESS';
export const LOAD_USERDATA_BYNAME_ACTION_FAILURE  = 'LOAD_USERDATA_BYNAME_ACTION_FAILURE';
export const UPDATE_USERDATA_ACTION = 'UPDATE_USERDATA_ACTION';
export const UPDATE_USERDATA_ACTION_SUCCESS = 'UPDATE_USERDATA_ACTION_SUCCESS';
export const UPDATE_USERDATA_ACTION_FAILURE = 'UPDATE_USERDATA_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';
