export const LOAD_COUNTRIES_ACTION = 'LOAD_COUNTRIES_ACTION';
export const LOAD_COUNTRIES_ACTION_SUCCESS = 'LOAD_COUNTRIES_ACTION_SUCCESS';
export const LOAD_COUNTRIES_ACTION_FAILURE = 'LOAD_COUNTRIES_ACTION_FAILURE';

export const LOAD_TABLES_ACTION = 'LOAD_TABLES_ACTION';
export const LOAD_TABLES_ACTION_SUCCESS = 'LOAD_TABLES_ACTION_SUCCESS';
export const LOAD_TABLES_ACTION_FAILURE = 'LOAD_TABLES_ACTION_FAILURE';

export const LOAD_COMPANIES_ACTION = 'LOAD_COMPANIES_ACTION';
export const LOAD_COMPANIES_ACTION_SUCCESS = 'LOAD_COMPANIES_ACTION_SUCCESS';
export const LOAD_COMPANIES_ACTION_FAILURE = 'LOAD_COMPANIES_ACTION_FAILURE';

export const LOAD_OPERATORSTATUS_ACTION = 'LOAD_OPERATORSTATUS_ACTION';
export const LOAD_OPERATORSTATUS_ACTION_SUCCESS = 'LOAD_OPERATORSTATUS_ACTION_SUCCESS';
export const LOAD_OPERATORSTATUS_ACTION_FAILURE = 'LOAD_OPERATORSTATUS_ACTION_FAILURE';

export const LOAD_LOOKFEELS_ACTION = 'LOAD_LOOKFEELS_ACTION';
export const LOAD_LOOKFEELS_ACTION_SUCCESS = 'LOAD_LOOKFEELS_ACTION_SUCCESS';
export const LOAD_LOOKFEELS_ACTION_FAILURE = 'LOAD_LOOKFEELS_ACTION_FAILURE';

export const LOAD_AUTHENTICATIONTYPE_ACTION = 'LOAD_AUTHENTICATIONTYPE_ACTION';
export const LOAD_AUTHENTICATIONTYPE_ACTION_SUCCESS = 'LOAD_AUTHENTICATIONTYPE_ACTION_SUCCESS';
export const LOAD_AUTHENTICATIONTYPE_ACTION_FAILURE = 'LOAD_AUTHENTICATIONTYPE_ACTION_FAILURE';


export const LOAD_USERTYPE_ACTION = 'LOAD_USERTYPE_ACTION';
export const LOAD_USERTYPE_ACTION_SUCCESS = 'LOAD_USERTYPE_ACTION_SUCCESS';
export const LOAD_USERTYPE_ACTION_FAILURE = 'LOAD_USERTYPE_ACTION_FAILURE';

export const LOAD_ROLE_ACTION = 'LOAD_ROLE_ACTION';
export const LOAD_ROLE_ACTION_SUCCESS = 'LOAD_ROLE_ACTION_SUCCESS';
export const LOAD_ROLE_ACTION_FAILURE = 'LOAD_ROLE_ACTION_FAILURE';

export const LOAD_PROFILE_ACTION = 'LOAD_PROFILE_ACTION';
export const LOAD_PROFILE_ACTION_SUCCESS = 'LOAD_PROFILE_ACTION_SUCCESS';
export const LOAD_PROFILE_ACTION_FAILURE = 'LOAD_PROFILE_ACTION_FAILURE';

export const LOAD_CARRIER_ACTION = 'LOAD_CARRIER_ACTION';
export const LOAD_CARRIER_ACTION_SUCCESS = 'LOAD_CARRIER_ACTION_SUCCESS';
export const LOAD_CARRIER_ACTION_FAILURE = 'LOAD_CARRIER_ACTION_FAILURE';

export const LOAD_TECHNOLOGY_ACTION = 'LOAD_TECHNOLOGY_ACTION';
export const LOAD_TECHNOLOGY_ACTION_SUCCESS = 'LOAD_TECHNOLOGY_ACTION_SUCCESS';
export const LOAD_TECHNOLOGY_ACTION_FAILURE = 'LOAD_TECHNOLOGY_ACTION_FAILURE';

export const LOAD_CAMPAIGNSTATUS_ACTION = 'LOAD_CAMPAIGNSTATUS_ACTION';
export const LOAD_CAMPAIGNSTATUS_ACTION_SUCCESS = 'LOAD_CAMPAIGNSTATUS_ACTION_SUCCESS';
export const LOAD_CAMPAIGNSTATUS_ACTION_FAILURE = 'LOAD_CAMPAIGNSTATUS_ACTION_FAILURE';

export const LOAD_FREEVIEWS_ACTION = 'LOAD_FREEVIEWS_ACTION';
export const LOAD_FREEVIEWS_ACTION_SUCCESS = 'LOAD_FREEVIEWS_ACTION_SUCCESS';
export const LOAD_FREEVIEWS_ACTION_FAILURE = 'LOAD_FREEVIEWS_ACTION_FAILURE';

export const LOAD_CAMPAINGS_ACTION = 'LOAD_CAMPAINGS_ACTION';
export const LOAD_CAMPAINGS_ACTION_SUCCESS = 'LOAD_CAMPAINGS_ACTION_SUCCESS';
export const LOAD_CAMPAINGS_ACTION_FAILURE = 'LOAD_CAMPAINGS_ACTION_FAILURE';
