/*
 *
 * LurinFvLookFeelContainer constants
 *
 */

export const LOAD_LOOKFEELS_ACTION = 'LOAD_LOOKFEELS_ACTION';
export const LOAD_LOOKFEELS_ACTION_SUCCESS = 'LOAD_LOOKFEELS_ACTION_SUCCESS';
export const LOAD_LOOKFEELS_ACTION_FAILURE = 'LOAD_LOOKFEELS_ACTION_FAILURE';
export const SHOW_LOOKFEELS_FORM_ACTION = 'SHOW_LOOKFEELS_FORM_ACTION';
export const CREATE_LOOKFEELS_ACTION = 'CREATE_LOOKFEELS_ACTION';
export const CREATE_LOOKFEELS_ACTION_SUCCESS = 'CREATE_LOOKFEELS_ACTION_SUCCESS';
export const CREATE_LOOKFEELS_ACTION_FAILURE = 'CREATE_LOOKFEELS_ACTION_FAILURE';
export const UPDATE_LOOKFEELS_ACTION = 'UPDATE_LOOKFEELS_ACTION';
export const UPDATE_LOOKFEELS_ACTION_SUCCESS = 'UPDATE_LOOKFEELS_ACTION_SUCCESS';
export const UPDATE_LOOKFEELS_ACTION_FAILURE = 'UPDATE_LOOKFEELS_ACTION_FAILURE';
export const DELETE_LOOKFEELS_ACTION = 'DELETE_LOOKFEELS_ACTION';
export const DELETE_LOOKFEELS_ACTION_SUCCESS = 'DELETE_LOOKFEELS_ACTION_SUCCESS';
export const DELETE_LOOKFEELS_ACTION_FAILURE = 'DELETE_LOOKFEELS_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';
