/*
 *
 * LurinFvCampaingContainer constants
 *
 */

export const LOAD_STORAGES_ACTION = 'LOAD_STORAGES_ACTION';
export const LOAD_STORAGES_ACTION_SUCCESS = 'LOAD_STORAGES_ACTION_SUCCESS';
export const LOAD_STORAGES_ACTION_FAILURE = 'LOAD_STORAGES_ACTION_FAILURE';
export const SHOW_STORAGES_FORM_ACTION = 'SHOW_STORAGES_FORM_ACTION';
export const RESET_ALERT_MESSAGE_ACTION = 'RESET_ALERT_MESSAGE_ACTION';
export const CREATE_STORAGES_ACTION = 'CREATE_STORAGES_ACTION';
export const CREATE_STORAGES_ACTION_SUCCESS = 'CREATE_STORAGES_ACTION_SUCCESS';
export const CREATE_STORAGES_ACTION_FAILURE = 'CREATE_STORAGES_ACTION_FAILURE';
export const UPDATE_STORAGES_ACTION = 'UPDATE_STORAGES_ACTION';
export const UPDATE_STORAGES_ACTION_SUCCESS = 'UPDATE_STORAGES_ACTION_SUCCESS';
export const UPDATE_STORAGES_ACTION_FAILURE = 'UPDATE_STORAGES_ACTION_FAILURE';
export const DELETE_STORAGES_ACTION = 'DELETE_STORAGES_ACTION';
export const DELETE_STORAGES_ACTION_SUCCESS = 'DELETE_STORAGES_ACTION_SUCCESS';
export const DELETE_STORAGES_ACTION_FAILURE = 'DELETE_STORAGES_ACTION_FAILURE';

export const LOAD_SOURCETYPES_ACTION = 'LOAD_SOURCETYPES_ACTION';
export const LOAD_SOURCETYPES_ACTION_SUCCESS = 'LOAD_SOURCETYPES_ACTION_SUCCESS';
export const LOAD_SOURCETYPES_ACTION_FAILURE = 'LOAD_SOURCETYPES_ACTION_FAILURE';

export const LOAD_STATUS_ACTION = 'LOAD_STATUS_ACTION';
export const LOAD_STATUS_ACTION_SUCCESS = 'LOAD_STATUS_ACTION_SUCCESS';
export const LOAD_STATUS_ACTION_FAILURE = 'LOAD_STATUS_ACTION_FAILURE';

export const SEND_TESTDS_ACTION = 'SEND_TESTDS_ACTION';
export const SEND_TESTDS_ACTION_SUCCESS = 'SEND_TESTDS_ACTION_SUCCESS';
export const SEND_TESTDS_ACTION_FAILURE = 'SEND_TESTDS_ACTION_FAILURE';

export const INIT_TESTDS_ACTION = 'INIT_TESTDS_ACTION';
export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';

