/*
 *
 * LurinFvGlobalParameterContainer constants
 *
 */

export const LOAD_GLOBALPARAMETERS_ACTION = 'LOAD_GLOBALPARAMETERS_ACTION';
export const LOAD_GLOBALPARAMETERS_ACTION_SUCCESS = 'LOAD_GLOBALPARAMETERS_ACTION_SUCCESS';
export const LOAD_GLOBALPARAMETERS_ACTION_FAILURE = 'LOAD_GLOBALPARAMETERS_ACTION_FAILURE';
export const SHOW_GLOBALPARAMETERS_FORM_ACTION = 'SHOW_GLOBALPARAMETERS_FORM_ACTION';
export const CREATE_GLOBALPARAMETERS_ACTION = 'CREATE_GLOBALPARAMETERS_ACTION';
export const CREATE_GLOBALPARAMETERS_ACTION_SUCCESS = 'CREATE_GLOBALPARAMETERS_ACTION_SUCCESS';
export const CREATE_GLOBALPARAMETERS_ACTION_FAILURE = 'CREATE_GLOBALPARAMETERS_ACTION_FAILURE';
export const UPDATE_GLOBALPARAMETERS_ACTION = 'UPDATE_GLOBALPARAMETERS_ACTION';
export const UPDATE_GLOBALPARAMETERS_ACTION_SUCCESS = 'UPDATE_GLOBALPARAMETERS_ACTION_SUCCESS';
export const UPDATE_GLOBALPARAMETERS_ACTION_FAILURE = 'UPDATE_GLOBALPARAMETERS_ACTION_FAILURE';
export const DELETE_GLOBALPARAMETERS_ACTION = 'DELETE_GLOBALPARAMETERS_ACTION';
export const DELETE_GLOBALPARAMETERS_ACTION_SUCCESS = 'DELETE_GLOBALPARAMETERS_ACTION_SUCCESS';
export const DELETE_GLOBALPARAMETERS_ACTION_FAILURE = 'DELETE_GLOBALPARAMETERS_ACTION_FAILURE';


export const LOAD_GP_CATEGORIES_ACTION = 'LOAD_GP_CATEGORIES_ACTION';
export const LOAD_GP_CATEGORIES_ACTION_SUCCESS = 'LOAD_GP_CATEGORIES_ACTION_SUCCESS';
export const LOAD_GP_CATEGORIES_ACTION_FAILURE = 'LOAD_GP_CATEGORIES_ACTION_FAILURE';

export const INIT_MESSAGE_ACTION = 'INIT_MESSAGE_ACTION';