export const LOAD_PACKAGES_BY_CARRIER_ACTION = 'LOAD_PACKAGES_BY_CARRIER_ACTION';
export const LOAD_PACKAGES_BY_CARRIER_ACTION_SUCCESS = 'LOAD_PACKAGES_BY_CARRIER_ACTION_SUCCESS';
export const LOAD_PACKAGES_BY_CARRIER_ACTION_FAILURE = 'LOAD_PACKAGES_BY_CARRIER_ACTION_FAILURE';

export const LOAD_TECHNOLOGY_ACTION = 'LOAD_TECHNOLOGY_ACTION';
export const LOAD_TECHNOLOGY_ACTION_SUCCESS = 'LOAD_TECHNOLOGY_ACTION_SUCCESS';
export const LOAD_TECHNOLOGY_ACTION_FAILURE = 'LOAD_TECHNOLOGY_ACTION_FAILURE';

/** * INIT CAMPAIGN   */

export const LOAD_ZONES_ACTION = 'LOAD_ZONES_ACTION';
export const LOAD_ZONES_ACTION_SUCCESS = 'LOAD_ZONES_ACTION_SUCCESS';
export const LOAD_ZONES_ACTION_FAILURE = 'LOAD_ZONES_ACTION_FAILURE';

export const LOAD_LOADTYPES_ACTION = 'LOAD_LOADTYPES_ACTION';
export const LOAD_LOADTYPES_ACTION_SUCCESS = 'LOAD_LOADTYPES_ACTION_SUCCESS';
export const LOAD_LOADTYPES_ACTION_FAILURE = 'LOAD_LOADTYPES_ACTION_FAILURE';

export const LOAD_MESSAGES_ACTION = 'LOAD_MESSAGES_ACTION';
export const LOAD_MESSAGES_ACTION_SUCCESS = 'LOAD_MESSAGES_ACTION_SUCCESS';
export const LOAD_MESSAGES_ACTION_FAILURE = 'LOAD_MESSAGES_ACTION_FAILURE';

export const LOAD_CAMPAIGNSTATUS_ACTION = 'LOAD_CAMPAIGNSTATUS_ACTION';
export const LOAD_CAMPAIGNSTATUS_ACTION_SUCCESS = 'LOAD_CAMPAIGNSTATUS_ACTION_SUCCESS';
export const LOAD_CAMPAIGNSTATUS_ACTION_FAILURE = 'LOAD_CAMPAIGNSTATUS_ACTION_FAILURE';


export const LOAD_CARRIERBYCODE_ACTION = 'LOAD_CARRIERBYCODE_ACTION';
export const LOAD_CARRIERBYCODE_ACTION_SUCCESS = 'LOAD_CARRIERBYCODE_ACTION_SUCCESS';
export const LOAD_CARRIERBYCODE_ACTION_FAILURE = 'LOAD_CARRIERBYCODE_ACTION_FAILURE';

/** * END CAMPAIGN   */
